# DataSource configuration
spring.datasource.url=jdbc:sqlserver://localhost\\sqldeveloper:1433;encrypt=true;trustServerCertificate=true;databaseName=db_agenda
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=senac

# JPA/Hibernate properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Specify the dialect for the database
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
